
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.lang.NullPointerException;
import java.util.HashMap;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author DELL
 */
public class Student_Detail extends javax.swing.JFrame {
    

 Connection cn=null;
Statement st=null;
String gender="";
 String experience="";
 String e_id="";
 ResultSet rs=null;
 String doj="";
 Boolean check;
 String path="";
 String imgname="";

    
    public Student_Detail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txt_fname = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_Mob = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        DOB = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("        Student Detail");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 209, 45));

        jLabel4.setText("Emp Id");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 40, -1));

        jLabel5.setText("First Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        jLabel7.setText("Last Name");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jLabel8.setText("Address");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 58, -1));

        jLabel9.setText("DAte Of Birth");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        jLabel10.setText("Gender");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, -1));

        jLabel11.setText("Mob No");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, -1, -1));

        jButton3.setText("Insert");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 620, 86, -1));

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 620, 86, -1));

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 620, 86, -1));

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 620, 90, -1));

        txt_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fnameActionPerformed(evt);
            }
        });
        txt_fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fnameKeyPressed(evt);
            }
        });
        jPanel2.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 132, -1));

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_idKeyPressed(evt);
            }
        });
        jPanel2.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 132, -1));

        txt_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lnameActionPerformed(evt);
            }
        });
        txt_lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_lnameKeyPressed(evt);
            }
        });
        jPanel2.add(txt_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 132, -1));

        txt_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addressActionPerformed(evt);
            }
        });
        txt_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_addressKeyPressed(evt);
            }
        });
        jPanel2.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 132, -1));

        txt_Mob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MobActionPerformed(evt);
            }
        });
        txt_Mob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_MobKeyPressed(evt);
            }
        });
        jPanel2.add(txt_Mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 132, -1));

        male.setText("male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel2.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, -1, -1));

        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel2.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, -1, -1));

        DOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DOBKeyPressed(evt);
            }
        });
        jPanel2.add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 132, -1));

        jButton1.setLabel("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 620, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mscit/image2.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        if(female.isSelected()==true)
        {
            gender="Female";
            male.setSelected(false);
        }
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        if(male.isSelected()==true)
        {
            gender="Male";
            female.setSelected(false);
        }
    }//GEN-LAST:event_maleActionPerformed

    private void txt_MobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MobKeyPressed
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' && txt_Mob.getText().length()<10 || evt.getKeyCode() == evt.VK_BACK_SPACE)
        {

            txt_Mob.setEditable(true);

        }
        else
        {
            txt_Mob.setEditable(false);

        }
    }//GEN-LAST:event_txt_MobKeyPressed

    private void txt_MobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MobActionPerformed

    private void txt_addressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_addressKeyPressed
        if (Character.isAlphabetic(evt.getKeyChar()) || evt.getKeyCode() == evt.VK_BACK_SPACE  || evt.getKeyCode()==32 || evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')
        {
            txt_address.setEditable(true);

        }
        else
        {
            txt_address.setEditable(false);

        }
    }//GEN-LAST:event_txt_addressKeyPressed

    private void txt_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addressActionPerformed

    }//GEN-LAST:event_txt_addressActionPerformed

    private void txt_lnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lnameKeyPressed
        if (Character.isAlphabetic(evt.getKeyChar())  || evt.getKeyCode()==46 || evt.getKeyCode()==32 || evt.getKeyCode() == evt.VK_BACK_SPACE)
        {
            txt_lname.setEditable(true);

        }
        else
        {
            txt_lname.setEditable(false);

        }
    }//GEN-LAST:event_txt_lnameKeyPressed

    private void txt_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lnameActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lnameActionPerformed

    private void txt_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyPressed
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == evt.VK_BACK_SPACE)
        {

            txt_id.setEditable(true);

        }
        else
        {
            txt_id.setEditable(false);

        }
    }//GEN-LAST:event_txt_idKeyPressed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_fnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fnameKeyPressed
        if (Character.isAlphabetic(evt.getKeyChar())  || evt.getKeyCode()==46 || evt.getKeyCode()==32 || evt.getKeyCode() == evt.VK_BACK_SPACE)
        {
            txt_fname.setEditable(true);

        }
        else
        {
            txt_fname.setEditable(false);

        }
    }//GEN-LAST:event_txt_fnameKeyPressed

    private void txt_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fnameActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fnameActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int p =JOptionPane.showConfirmDialog(null, "Do you want to really Deleted", "Delete",JOptionPane.YES_NO_OPTION);
        if(p==0)
        {

            try
            {
                st=cn.createStatement();
                String sql="delete from userdb where Id='"+txt_id.getText().toString()+"'";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Record Deleted Successfully");

                txt_fname.setText(null);
                txt_lname.setText(null);
                txt_address.setText(null);
                male.setSelected(false);
                female.setSelected(false);
                DOB.setDate(null);
                txt_Mob.setText(null);
            }catch(Exception ex)
            {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int p =JOptionPane.showConfirmDialog(null, "Do you want to really updated", "Updated",JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
            SimpleDateFormat formatter=new SimpleDateFormat("yyyy:MM:dd");
            String doj=formatter.format(DOB.getDate());

            try
            {
                st.close();
                st=cn.createStatement();
                String sql="update userdb set First_Name='"+txt_fname.getText().toString()+"',Last_Name='"+txt_lname.getText().toString()+"',Address='"+txt_address.getText().toString()+"',DOB='"+doj+"',gender='"+gender.toString()+"',Mob_no='"+txt_Mob.getText().toString()+"' where ID='"+txt_id.getText().toString()+"'";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Record Update Successfully");
                txt_fname.setText(null);
                txt_lname.setText(null);
                txt_address.setText(null);
                male.setSelected(false);
                female.setSelected(false);
                txt_Mob.setText(null);
                
                
            }catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex);
            }

        }else
            
        {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(txt_fname.getText().length()==0||txt_fname.getText().length()==0||txt_address.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Some fields are empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(txt_Mob.getText().length()!=10)
        {
            JOptionPane.showMessageDialog(null, "Invalid contact No","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {

        SimpleDateFormat formatter=new SimpleDateFormat("YYYY-MM-dd");
        String doj=formatter.format(DOB.getDate());
        try
        {
            st.close();
            st=cn.createStatement();
            String sql="insert into userdb(First_Name,Last_Name,Address,DOB,Gender,Mob_no)values('"+txt_fname.getText().toString()+"','"+txt_lname.getText().toString()+"','"+txt_address.getText().toString()+"','"+doj+"','"+gender.toString()+"','"+txt_Mob.getText().toString()+"')";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Record Insert Successfully");
            txt_address.setText(null);
            male.setSelected(false);
            female.setSelected(false);
            txt_Mob.setText(null);
            txt_fname.setText(null);
            txt_lname.setText(null);
            txt_Mob.setText(null);
            DOB.setDate(null);

        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       try
{
Class.forName("com.mysql.jdbc.Driver");

cn = DriverManager.getConnection("jdbc:mysql://localhost/empdb","root", "");
st=cn.createStatement();
System.out.print("Database is connected !");

}
catch(Exception e)
{
System.out.print("Do not connect to DB - Error:"+e);
}
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       txt_id.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(false);
   String gender1="";
        String exeperience="";
        txt_address.setText(null);
        male.setSelected(false);
        female.setSelected(false);
        txt_fname.setText(null);
        txt_Mob.setText(null);
        txt_lname.setText(null);
        
        try
       
        {
            //JOptionPane.showMessageDialog(null, txt_id.getText());
           // st.close();
            st=cn.createStatement();
            String sql="select * from userdb where ID='"+txt_id.getText().toString()+"'";
            rs=st.executeQuery(sql);
            //  String sn=rs.getString("date_of_joining");
            if(rs.next())
            {

                txt_fname.setText(rs.getString("First_Name"));
                txt_lname.setText(rs.getString("Last_Name"));
                txt_address.setText(rs.getString("Address"));
                gender1=rs.getString("gender");
                txt_Mob.setText(rs.getString("Mob_no"));
                DOB.setDate(rs.getDate("DOB"));
                // String sn=rs.getString("date_of_joining");
                //((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(sn);

               if(gender1.equals("male"))
                {
                    male.setSelected(true);
                }
                if(gender1.equals("Female"))
                {
                    female.setSelected(true);
                }
               
               
                

            }
            else
            {
                // e_id=String.valueOf(Integer.parseInt(e_id)+1);
                // txt_id.setText(e_id);
                txt_address.setText(null);
                
                txt_Mob.setText(null);
                
               
                txt_fname.setText(null);
                txt_lname.setText(null);
               
                
                jButton3.setEnabled(false);
                jButton4.setEnabled(false);
                jButton5.setEnabled(false);
            }
            st.close();
        }catch(Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DOBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DOBKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Detail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DOB;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField txt_Mob;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_lname;
    // End of variables declaration//GEN-END:variables
}
